import { htmlToText } from "html-to-text";

type StructuredSection = {
  heading: string;
  body: string;
  bullets?: string[];
};

type StructuredDocument = {
  title: string;
  sections: StructuredSection[];
};

type Slide = {
  title: string;
  content: string;
  bullets?: string[];
  slideType: "title" | "content" | "bullets" | "conclusion";
};

type SlideDocument = {
  title: string;
  subtitle?: string;
  slides: Slide[];
};

type ExcelSheet = {
  name: string;
  headers: string[];
  rows: (string | number)[][];
  chartType?: "bar" | "pie" | "line";
  chartTitle?: string;
};

type ExcelDocument = {
  title: string;
  sheets: ExcelSheet[];
};

function stripTags(value: string) {
  return value.replace(/<[^>]*>/g, " ").replace(/\s+/g, " ").trim();
}

function toPlainText(content: string) {
  const plain = htmlToText(content, {
    selectors: [{ selector: "a", options: { ignoreHref: true } }],
    wordwrap: false,
  }).trim();

  return plain || stripTags(content) || "No content provided.";
}

export function htmlToStructuredSections(content: string): StructuredSection[] {
  const headingPattern = /<h[2-6][^>]*>([\s\S]*?)<\/h[2-6]>/gi;
  const parts = content.split(headingPattern);
  const sections: StructuredSection[] = [];

  if (parts.length === 1) {
    return [{ heading: "Content", body: toPlainText(content) }];
  }

  const intro = toPlainText(parts[0] || "");
  if (intro && intro !== "No content provided.") {
    sections.push({ heading: "Introduction", body: intro });
  }

  for (let index = 1; index < parts.length; index += 2) {
    const heading = stripTags(parts[index]) || "Section";
    const bodyHtml = parts[index + 1] || "";
    const bullets = Array.from(bodyHtml.matchAll(/<li[^>]*>([\s\S]*?)<\/li>/gi))
      .map((match) => stripTags(match[1]))
      .filter(Boolean);
    const body = toPlainText(bodyHtml).replace(/\n{3,}/g, "\n\n").trim();

    sections.push({
      heading,
      body: body || " ",
      bullets: bullets.length ? bullets : undefined,
    });
  }

  return sections.length ? sections : [{ heading: "Content", body: stripTags(content) || "No content provided." }];
}

export function htmlToStructuredDocument(content: string, fallbackTitle = "Document"): StructuredDocument {
  const titleMatch = content.match(/<h1[^>]*>([\s\S]*?)<\/h1>/i);
  const title = stripTags(titleMatch?.[1] || "") || fallbackTitle;
  const contentWithoutTitle = content.replace(/<h1[^>]*>[\s\S]*?<\/h1>/i, "").trim();

  return {
    title,
    sections: htmlToStructuredSections(contentWithoutTitle || content),
  };
}

export function htmlToSlides(content: string, fallbackTitle = "Presentation"): SlideDocument {
  const document = htmlToStructuredDocument(content, fallbackTitle);
  const contentSections = document.sections.filter(
    (section) => section.body.trim() && section.body.trim() !== "No content provided.",
  );

  const slides: Slide[] = [
    {
      title: document.title,
      content: contentSections[0]?.body || "Presentation generated by DocGenius AI.",
      slideType: "title",
    },
  ];

  for (const [index, section] of contentSections.entries()) {
    slides.push({
      title: section.heading || `Slide ${index + 2}`,
      content: section.body || " ",
      bullets: section.bullets?.length ? section.bullets.slice(0, 5) : undefined,
      slideType:
        index === contentSections.length - 1
          ? "conclusion"
          : section.bullets?.length
            ? "bullets"
            : "content",
    });
  }

  return {
    title: document.title,
    subtitle: contentSections[0]?.heading && contentSections[0].heading !== "Introduction" ? contentSections[0].heading : undefined,
    slides,
  };
}

export function htmlToWorkbook(content: string, fallbackTitle = "Spreadsheet"): ExcelDocument {
  const document = htmlToStructuredDocument(content, fallbackTitle);
  const sections = document.sections.length
    ? document.sections
    : [{ heading: "Overview", body: "No content provided.", bullets: [] }];

  const sheets: ExcelSheet[] = sections.map((section, index) => {
    const bullets = section.bullets?.filter(Boolean) ?? [];
    const paragraphRows = section.body
      .split(/\n+/)
      .map((line) => line.trim())
      .filter((line) => line && line !== "No content provided.")
      .map((line, rowIndex) => [`Point ${rowIndex + 1}`, line]);

    const bulletRows = bullets.map((bullet, rowIndex) => [`Bullet ${rowIndex + 1}`, bullet]);
    const rows = [...paragraphRows, ...bulletRows];

    return {
      name: sanitizeSheetName(section.heading || `Sheet ${index + 1}`),
      headers: ["Label", "Details"],
      rows: rows.length ? rows : [["Point 1", section.body || "No content provided."]],
      chartType: rows.length >= 2 ? "bar" : undefined,
      chartTitle: rows.length >= 2 ? `${section.heading || `Sheet ${index + 1}`} Summary` : undefined,
    };
  });

  return {
    title: document.title,
    sheets,
  };
}

function sanitizeSheetName(name: string) {
  return name.replace(/[\\/*?:[\]]/g, " ").replace(/\s+/g, " ").trim().slice(0, 31) || "Sheet";
}
