from fastapi import APIRouter, HTTPException
from fastapi.responses import Response
from pydantic import BaseModel
from typing import Optional, List, Literal, Union
import io
import openpyxl
from openpyxl import Workbook
from openpyxl.styles import (
    PatternFill, Font, Alignment, Border, Side, GradientFill
)
from openpyxl.chart import BarChart, PieChart, LineChart, Reference
from openpyxl.chart.series import DataPoint
from openpyxl.utils import get_column_letter

router = APIRouter()

BRAND_BLUE = "4C6EF5"
BRAND_VIOLET = "7C3AED"
BRAND_DARK = "0F0F1A"
LIGHT_BG = "EEF2FF"
HEADER_BG = "1a1a2e"
ROW_ALT = "F8F9FF"


class Sheet(BaseModel):
    name: str
    headers: List[str]
    rows: List[List[Union[str, int, float]]]
    chartType: Optional[Literal["bar", "pie", "line"]] = None
    chartTitle: Optional[str] = None


class ExcelRequest(BaseModel):
    title: str
    sheets: List[Sheet]


@router.post("/xlsx")
async def generate_excel(req: ExcelRequest):
    try:
        wb = Workbook()
        wb.remove(wb.active)  # remove default sheet

        for sheet_data in req.sheets:
            ws = wb.create_sheet(title=sheet_data.name[:31])

            # Title row
            ws.merge_cells(start_row=1, start_column=1, end_row=1, end_column=len(sheet_data.headers))
            title_cell = ws.cell(row=1, column=1, value=req.title)
            title_cell.fill = PatternFill("solid", fgColor=BRAND_BLUE)
            title_cell.font = Font(bold=True, size=14, color="FFFFFF", name="Calibri")
            title_cell.alignment = Alignment(horizontal="center", vertical="center")
            ws.row_dimensions[1].height = 30

            # Subtitle row
            ws.merge_cells(start_row=2, start_column=1, end_row=2, end_column=len(sheet_data.headers))
            sub_cell = ws.cell(row=2, column=1, value=f"{sheet_data.name} | Generated by DocGenius AI")
            sub_cell.fill = PatternFill("solid", fgColor=BRAND_VIOLET)
            sub_cell.font = Font(size=9, color="E8E8F0", name="Calibri")
            sub_cell.alignment = Alignment(horizontal="center")
            ws.row_dimensions[2].height = 18

            # Header row
            header_row = 3
            for col_idx, header in enumerate(sheet_data.headers, start=1):
                cell = ws.cell(row=header_row, column=col_idx, value=header)
                cell.fill = PatternFill("solid", fgColor=HEADER_BG)
                cell.font = Font(bold=True, color="FFFFFF", size=11, name="Calibri")
                cell.alignment = Alignment(horizontal="center", vertical="center")
                cell.border = Border(
                    bottom=Side(style="medium", color=BRAND_BLUE)
                )
                # Auto width
                ws.column_dimensions[get_column_letter(col_idx)].width = max(15, len(header) + 4)
            ws.row_dimensions[header_row].height = 24

            # Data rows
            for row_idx, row_data in enumerate(sheet_data.rows, start=header_row + 1):
                is_alt = (row_idx - header_row) % 2 == 0
                for col_idx, value in enumerate(row_data, start=1):
                    cell = ws.cell(row=row_idx, column=col_idx, value=value)
                    cell.fill = PatternFill("solid", fgColor=ROW_ALT if is_alt else "FFFFFF")
                    cell.font = Font(size=11, name="Calibri")
                    cell.alignment = Alignment(horizontal="center" if isinstance(value, (int, float)) else "left")
                    cell.border = Border(
                        bottom=Side(style="thin", color="E5E7EB")
                    )
                ws.row_dimensions[row_idx].height = 20

            # Chart
            if sheet_data.chartType and sheet_data.rows:
                data_start = header_row
                data_end = header_row + len(sheet_data.rows)
                chart_col = len(sheet_data.headers) + 2

                if sheet_data.chartType == "bar":
                    chart = BarChart()
                    chart.type = "col"
                    chart.grouping = "clustered"
                    chart.title = sheet_data.chartTitle or sheet_data.name
                    chart.style = 10
                elif sheet_data.chartType == "pie":
                    chart = PieChart()
                    chart.title = sheet_data.chartTitle or sheet_data.name
                    chart.style = 10
                else:  # line
                    chart = LineChart()
                    chart.title = sheet_data.chartTitle or sheet_data.name
                    chart.style = 10

                # Data references (second column onwards)
                data_ref = Reference(ws, min_col=2, min_row=data_start, max_col=len(sheet_data.headers), max_row=data_end)
                cats = Reference(ws, min_col=1, min_row=data_start + 1, max_row=data_end)

                chart.add_data(data_ref, titles_from_data=True)
                chart.set_categories(cats)
                chart.shape = 4
                chart.width = 20
                chart.height = 14

                ws.add_chart(chart, f"{get_column_letter(chart_col)}{header_row}")

        # Summary sheet
        ws_summary = wb.create_sheet(title="Summary", index=0)
        ws_summary.cell(row=1, column=1, value="📊 DocGenius AI — Excel Report").font = Font(bold=True, size=16, color=BRAND_BLUE, name="Calibri")
        ws_summary.cell(row=2, column=1, value=req.title).font = Font(size=12, name="Calibri")
        ws_summary.cell(row=3, column=1, value=f"Sheets: {len(req.sheets)}").font = Font(size=11, color="6B7280", name="Calibri")
        ws_summary.column_dimensions["A"].width = 40

        buffer = io.BytesIO()
        wb.save(buffer)
        buffer.seek(0)

        return Response(
            content=buffer.read(),
            media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            headers={"Content-Disposition": f'attachment; filename="{req.title}.xlsx"'},
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
