from fastapi import APIRouter, HTTPException
from fastapi.responses import Response
from pydantic import BaseModel
from typing import Optional, List
import io
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, HRFlowable,
    ListFlowable, ListItem
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY

router = APIRouter()

BRAND_BLUE = colors.HexColor("#4C6EF5")
BRAND_VIOLET = colors.HexColor("#7C3AED")
BRAND_LIGHT = colors.HexColor("#EEF2FF")
TEXT_DARK = colors.HexColor("#1a1a2e")
TEXT_MUTED = colors.HexColor("#6B7280")


class Section(BaseModel):
    heading: str
    body: str
    bullets: Optional[List[str]] = None


class PDFRequest(BaseModel):
    title: str
    docType: Optional[str] = "pdf"
    sections: List[Section]
    metadata: Optional[dict] = None


@router.post("/pdf")
async def generate_pdf(req: PDFRequest):
    try:
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=A4,
            rightMargin=72,
            leftMargin=72,
            topMargin=72,
            bottomMargin=72,
            title=req.title,
        )

        styles = getSampleStyleSheet()

        # Custom styles
        title_style = ParagraphStyle(
            "CustomTitle",
            parent=styles["Title"],
            fontSize=28,
            textColor=BRAND_BLUE,
            spaceAfter=8,
            alignment=TA_CENTER,
            fontName="Helvetica-Bold",
        )
        subtitle_style = ParagraphStyle(
            "Subtitle",
            parent=styles["Normal"],
            fontSize=10,
            textColor=TEXT_MUTED,
            spaceAfter=20,
            alignment=TA_CENTER,
        )
        h1_style = ParagraphStyle(
            "H1",
            parent=styles["Heading1"],
            fontSize=16,
            textColor=BRAND_BLUE,
            spaceBefore=16,
            spaceAfter=8,
            fontName="Helvetica-Bold",
            borderPad=4,
        )
        body_style = ParagraphStyle(
            "BodyCustom",
            parent=styles["Normal"],
            fontSize=11,
            leading=18,
            spaceAfter=8,
            alignment=TA_JUSTIFY,
            textColor=TEXT_DARK,
        )
        bullet_style = ParagraphStyle(
            "Bullet",
            parent=styles["Normal"],
            fontSize=11,
            leading=16,
            leftIndent=16,
            spaceBefore=2,
            spaceAfter=2,
            textColor=TEXT_DARK,
        )
        meta_style = ParagraphStyle(
            "Meta",
            parent=styles["Normal"],
            fontSize=9,
            textColor=TEXT_MUTED,
            alignment=TA_CENTER,
            spaceAfter=4,
        )

        story = []

        # Title
        story.append(Paragraph(req.title, title_style))

        # Metadata
        author = req.metadata.get("author", "AI Document Generator") if req.metadata else "AI Document Generator"
        story.append(Paragraph(f"Generated by {author}  •  DocGenius AI", meta_style))
        story.append(HRFlowable(width="100%", thickness=2, color=BRAND_BLUE, spaceAfter=20))

        # Sections
        for section in req.sections:
            story.append(Paragraph(section.heading, h1_style))
            story.append(HRFlowable(width="40%", thickness=1, color=BRAND_LIGHT, spaceAfter=6))

            if section.body:
                story.append(Paragraph(section.body, body_style))

            if section.bullets:
                items = []
                for b in section.bullets:
                    items.append(ListItem(Paragraph(b, bullet_style), bulletColor=BRAND_BLUE, bulletType="bullet"))
                story.append(ListFlowable(items, bulletType="bullet", start="•"))

            story.append(Spacer(1, 12))

        # Build PDF
        doc.build(story)
        buffer.seek(0)

        return Response(
            content=buffer.read(),
            media_type="application/pdf",
            headers={"Content-Disposition": f'attachment; filename="{req.title}.pdf"'},
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
