from fastapi import APIRouter, HTTPException
from fastapi.responses import Response
from pydantic import BaseModel
from typing import Optional, List
import io
from docx import Document
from docx.shared import Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from html2docx import html2docx

router = APIRouter()


# -------------------------
# Models
# -------------------------
class Section(BaseModel):
    heading: str
    body: str
    bullets: Optional[List[str]] = None


class WordRequest(BaseModel):
    title: str
    docType: Optional[str] = "docx"
    sections: List[Section]
    metadata: Optional[dict] = None


# -------------------------
# API ROUTE
# -------------------------
@router.post("/docx")
async def generate_word(req: WordRequest):
    try:
        # Create base document
        doc = Document()

        # Base style
        style = doc.styles["Normal"]
        style.font.name = "Calibri"
        style.font.size = Pt(11)

        # Title
        title_para = doc.add_heading(req.title, level=0)
        title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        title_run = title_para.runs[0]
        title_run.font.color.rgb = RGBColor(0x4C, 0x6E, 0xF5)
        title_run.font.size = Pt(24)

        # Metadata
        if req.metadata:
            meta = doc.add_paragraph()
            meta.alignment = WD_ALIGN_PARAGRAPH.CENTER
            meta_run = meta.add_run(
                f"Author: {req.metadata.get('author', 'AI Document Generator')}"
            )
            meta_run.font.color.rgb = RGBColor(0x88, 0x88, 0x99)
            meta_run.font.size = Pt(9)

        doc.add_paragraph()

        # -------------------------
        # Convert HTML → DOCX
        # -------------------------
        for section in req.sections:

            # Section heading
            heading = doc.add_heading(section.heading, level=1)
            heading.runs[0].font.color.rgb = RGBColor(0x4C, 0x6E, 0xF5)

            if section.body:
                # Convert HTML to DOCX (BytesIO)
                docx_bytes = html2docx(section.body, title=req.title)

                # Load into temporary document
                temp_doc = Document(docx_bytes)

                # Merge into main document
                for element in temp_doc.element.body:
                    doc.element.body.append(element)

            # Fallback bullets
            if section.bullets:
                for bullet in section.bullets:
                    doc.add_paragraph(bullet, style="List Bullet")

            doc.add_paragraph()

        # Footer
        section_obj = doc.sections[0]
        footer = section_obj.footer
        footer_para = footer.paragraphs[0]
        footer_para.text = f"Generated by DocGenius AI  |  {req.title}"
        footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

        for run in footer_para.runs:
            run.font.size = Pt(8)
            run.font.color.rgb = RGBColor(0x88, 0x88, 0x99)

        # Save to memory
        buffer = io.BytesIO()
        doc.save(buffer)
        buffer.seek(0)

        return Response(
            content=buffer.read(),
            media_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            headers={
                "Content-Disposition": f'attachment; filename="{req.title}.docx"'
            },
        )

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))